### ISSUE TITLE
Update the site

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/razor-network-nuxt#2]
While the port was in development, I had to update the content of the website at https://github.com/razor-network/website-revision (https://razor.network)
This repo needs to be updated before it can be pushed to production.

**Comment by hrishikeshio** [comment]
@rajkharvar Will you have the bandwidth next week to update the site?

**Comment by rajkharvar** [comment]
can we schedule for next weekend? For a few days, I will be having a busy schedule.

**Comment by hrishikeshio** [comment]
No problem. Up to you. No urgency.

**Comment by hrishikeshio** [comment]
Done
