### ISSUE TITLE
Disable the fade in animation of the website

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/razor-network-nuxt#3]
The fade in animation of all the divs seems unnecessary. Disable it for now, but don't completely remove it.
(Note: I am not referring to the scrolling animation of the words in header div -Finance,Prediction markets, etc. I am referring to the fade in animation of logo, footer, buttons, etc.)

**Comment by rajkharvar** [comment]
Close this issue since all the divs animation are disabled.
